'use client';
import {useEffect,useMemo,useState} from 'react';
import '../football-hub.css';

const SUPABASE_URL='https://eujaafpddvdtxqpeodsp.supabase.co';
const SUPABASE_KEY='sb_publishable_bYwRjZVA31vDpmcb2CdeTA_gWPZq92R';

export default function FreePicksPage(){
 const[picks,setPicks]=useState([]),[fixtures,setFixtures]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/free_picks?published=eq.true&select=*&order=kickoff_at.asc.nullslast,created_at.desc`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`},cache:'no-store'}).then(r=>r.ok?r.json():[]),
  fetch('/api/fixtures?days=2',{cache:'no-store'}).then(r=>r.ok?r.json():{matches:[]})
 ]).then(([p,f])=>{if(active){setPicks(Array.isArray(p)?p:[]);setFixtures(f.matches||[])}}).catch(()=>{}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
 const logoFor=(team,home)=>{const n=norm(team);const m=fixtures.find(x=>norm(x.home)===n||norm(x.away)===n);if(!m)return null;return norm(m.home)===n?m.homeLogo:m.awayLogo};
 const groups=useMemo(()=>{const map=new Map();picks.forEach(p=>{const k=p.league||'Football';if(!map.has(k))map.set(k,[]);map.get(k).push(p)});return [...map.entries()]},[picks]);
 return <main className="freePicksPage">
  <header className="freePicksHeader"><a href="/" className="freePicksBrand"><img src="/assets/logo.jpeg" alt="Stamp It Football"/><span><b>STAMP IT</b><small>FOOTBALL</small></span></a><a href="/" className="backHome">← HOME</a></header>
  <section className="freePicksHero"><div className="eyebrow">STAMP IT FOOTBALL</div><h1>SATURDAY FREE PICKS</h1><p>Today’s football predictions — free for everyone.</p><div className="freeBadge">FREE PICKS · NO ACCOUNT REQUIRED</div></section>
  <section className="freePicksContent">{loading?<div className="empty compact">Loading today’s picks…</div>:!picks.length?<div className="empty compact">No free picks published right now. Check back soon.</div>:groups.map(([league,items])=><div className="freeLeague" key={league}><div className="freeLeagueTitle"><h2>{league}</h2><span>{items.length} PICKS</span></div><div className="freePickGrid">{items.map(p=>{const hl=logoFor(p.home_team,true),al=logoFor(p.away_team,false);return <article className="freePickCard" key={p.id}><div className="freeKickoff">{p.kickoff_at?new Date(p.kickoff_at).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'}):'TODAY'}<span className={`pickStatusEnhancer ${p.status||'pending'}`}>{(p.status||'pending').toUpperCase()}</span></div><div className="freeTeams"><div>{hl?<img src={hl} alt=""/>:<span className="logoFallback">⚽</span>}<b>{p.home_team}</b></div><strong>VS</strong><div>{al?<img src={al} alt=""/>:<span className="logoFallback">⚽</span>}<b>{p.away_team}</b></div></div><div className="freeCall"><small>{p.pick_type}</small><strong>{p.pick_value}</strong></div>{p.reasoning&&<p>{p.reasoning}</p>}</article>})}</div></div>)}</section>
  <footer><b>STAMP IT FOOTBALL</b><span>IT’S FOOTBALL, NOT SOCCER.</span><span>@stampitfootball</span></footer>
  <style jsx global>{`
   .freePicksPage{min-height:100vh;background:#061512;color:#eef7f3}.freePicksHeader{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 max(18px,calc((100vw - 1180px)/2));background:#071c18;border-bottom:1px solid #1c493f;position:sticky;top:0;z-index:20}.freePicksBrand{display:flex;align-items:center;gap:10px;color:white;text-decoration:none}.freePicksBrand img{width:48px;height:48px;border-radius:50%;object-fit:cover}.freePicksBrand span{display:flex;flex-direction:column;line-height:.95}.freePicksBrand b{font-size:18px}.freePicksBrand small{color:#36d3ba;font-weight:900;letter-spacing:2px}.backHome{color:#f7c84b;font-weight:900;text-decoration:none}.freePicksHero{text-align:center;padding:52px 18px 34px;background:radial-gradient(circle at 50% 0,#12493e 0,#071c18 55%,#061512 100%)}.freePicksHero h1{font-size:clamp(32px,6vw,62px);margin:7px 0;color:#fff}.freePicksHero p{color:#b8cec7;font-size:17px}.freeBadge{display:inline-block;margin-top:12px;padding:8px 13px;border:1px solid #347d6d;border-radius:999px;color:#55e5ca;font-weight:900;font-size:12px}.freePicksContent{max-width:1180px;margin:auto;padding:12px 18px 70px}.freeLeague{margin-top:30px}.freeLeagueTitle{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #245248;padding:0 2px 10px}.freeLeagueTitle h2{margin:0;font-size:22px}.freeLeagueTitle span{color:#f7c84b;font-size:11px;font-weight:900}.freePickGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.freePickCard{background:#0a211d;border:1px solid #1c493f;border-radius:14px;padding:16px;box-shadow:0 10px 28px #0003}.freeKickoff{display:flex;justify-content:space-between;color:#8eaaa2;font-size:11px;font-weight:900;text-transform:uppercase}.freeTeams{display:grid;grid-template-columns:1fr 34px 1fr;align-items:center;gap:8px;margin:18px 0}.freeTeams>div{display:flex;align-items:center;gap:9px;min-width:0}.freeTeams>div:last-child{justify-content:flex-end;text-align:right}.freeTeams img,.logoFallback{width:34px;height:34px;object-fit:contain;flex:0 0 34px}.logoFallback{display:grid;place-items:center;font-size:23px}.freeTeams b{font-size:14px}.freeTeams>strong{text-align:center;color:#59766e;font-size:11px}.freeCall{background:#061512;border-left:3px solid #f7c84b;border-radius:7px;padding:10px 12px;display:flex;flex-direction:column;gap:2px}.freeCall small{color:#8eaaa2;text-transform:uppercase;font-weight:900}.freeCall strong{color:#f7c84b;font-size:17px}.freePickCard p{color:#9eb6af;font-size:12px;line-height:1.45;margin:10px 2px 0}@media(max-width:700px){.freePickGrid{grid-template-columns:1fr}.freePicksHeader{height:62px}.freePicksBrand img{width:40px;height:40px}.freePicksHero{padding-top:38px}.freeTeams b{font-size:13px}}
  `}</style>
 </main>
}
